# Generated by Django 4.0.2 on 2022-02-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination',
            field=models.CharField(blank=True, choices=[(0, 'Gift'), (1, 'Borrow'), (2, 'Lend'), (3, 'Payment')], max_length=20),
        ),
    ]
